name: GH-CLI
on:
  schedule:
    - cron: '1 6 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:     
  build-package:
    runs-on: ubuntu-latest
    container: continuumio/anaconda3
    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@master
    - name: Build packages
      env:
        TOKEN: ${{secrets.ANACONDA_TOKEN}}
      run: | 
        bash create-gh-yaml.sh
